### ISSUE TITLE
Missing hands-on examples

### ISSUE THREAD

**Issue by Smith4170** [learn-cfinaweek/v2-content#1]
I like the updated look and feel to the site, but the hands-on examples are missing.  I was unfortunately mid-class when the updated content was pushed to the server and the hands-on material was no longer available.  I understand some of the examples were out of date, I had to make some addition changes to the code so it would run on ColdFusion 2018.  Any way to access the old material so I can continue the class with the hands-on examples?

**Comment by fmdano** [comment]
I'm sure we can figure something out...give us some time on this...
thanks for the input.
________________________________

**Comment by Smith4170** [comment]
@fmdano Thanks for your quick response.  Let me know if there's anything I can do to contribute.

**Comment by chrisbo** [comment]
http://learncfinaweek.com/course/index Windows step 7 items 1 & 2 produce the following errors:

Command "cfconfig: box install commandbox-cfconfig" cannot be resolved.

Command "bullet train: box install commandbox-bullet-train" cannot be resolved.

**Comment by cfvonner** [comment]
@chrisbo are you behind a firewall/proxy that filters web traffic?  Is https://forgebox.io blocked?

**Comment by chrisbo** [comment]
@cfvonner Oops! The instructions were not clear. I was trying to run:

cfconfig: box install commandbox-cfconfig
bullet train: box install commandbox-bullet-train

instead of:

box install commandbox-cfconfig
box install commandbox-bullet-train

Prefixing with 'box' seems redundant too. Please correct me if I am wrong.

My apologies to all for my error of not opening this issue as a separate issue too.

**Comment by cfvonner** [comment]
If you start CommandBox and stay inside the CommandBox shell, then yes, prefixing each command with `box` is redundant.  For people new to CommandBox that just want to execute the commands right from their OS terminal prompt, the `box install ...` is appropriate.
